export enum DownloadError {
  UNSUPPORTED_PROVIDER = 'UNSUPPORTED_PROVIDER',
  NO_STICKERS_FOUND = 'NO_STICKERS_FOUND',
  NO_FILES_DOWNLOADED = 'NO_FILES_DOWNLOADED',
  ABORTED = 'ABORTED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}
