export const ANIMATION_DETECTOR_TOKEN = 'ANIMATION_DETECTOR';
export const GIF_COMPRESSOR_TOKEN = 'GIF_COMPRESSOR';
export const TRIM_UTILITY_TOKEN = 'TRIM_UTILITY';
export const RESCALE_UTILITY_TOKEN = 'RESCALE_UTILITY';
export const FRAGMENT_UTILITY_TOKEN = 'FRAGMENT_UTILITY';
export const WEBP_CONVERTER_TOKEN = 'WEBP_CONVERTER';
export const IMAGE_PROCESSING_SERVICE_TOKEN = 'IMAGE_PROCESSING_SERVICE';

export const GIF_MAX_DURATION = 2.99;
export const GIF_TARGET_FPS = 30;
export const GIF_MIN_SPEED_FACTOR = 0.5;

export const TRIM_THRESHOLD = 10;

export const WEBP_QUALITY = 100;
export const WEBP_ALPHA_QUALITY = 100;
export const WEBP_EFFORT = 4;

export const APNG_SIGNATURE = Buffer.from([0x61, 0x63, 0x54, 0x4c]);
